<?php

declare(strict_types=1);

require dirname(__DIR__) . '/src/bootstrap.php';

final class PromptFlowVerifier
{
    private int $checks = 0;
    private ?string $temporarySqlitePath = null;

    public function run(): void
    {
        $this->prepareIsolatedStore();
        try {
            $store = new Store();
            $catalog = new UmaCatalog();
            $composer = new PromptComposer($catalog, $store);
            $auditor = new PromptAuditor($composer, $store);
            $character = $this->characterWithBaseLoraAndOutfit($store);

            $this->verifyGlobalCensorshipGuard($composer, $character);
            $this->verifyNsfwCensorshipGuard($composer, $character);
            $this->verifyLlmPolishRemovesCensorshipTags($composer);
            $this->verifyHiresInheritsFinalNegativePrompt();
            $this->verifyHardNsfwNoActIsNeutral($composer, $character);
            $this->verifyStrictActBlocksIncompatibleLora($auditor, $character);
            $this->verifyClothingLoraBlocksActiveOutfit($auditor, $character);
            $this->verifyPoseBlockedByStrictAct($auditor, $character);
            $this->verifyCharacterLoraIdentityConflict($auditor, $character);
            $this->verifyCompatibleSeriesMismatch($auditor, $character);
            $this->verifyFrontendAutoLlmFlow();

            echo "Prompt flow verification passed ({$this->checks} checks)." . PHP_EOL;
        } finally {
            $this->cleanupIsolatedStore();
        }
    }

    private function prepareIsolatedStore(): void
    {
        $useConfiguredDb = strtolower((string) getenv('VERIFY_PROMPT_FLOW_USE_CONFIGURED_DB'));
        if (in_array($useConfiguredDb, ['1', 'true', 'yes'], true)) {
            return;
        }

        $path = rtrim(sys_get_temp_dir(), DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . 'character-studio-verify-prompt-flow-' . getmypid() . '.sqlite';
        @unlink($path);
        putenv('DB_DRIVER=sqlite');
        putenv('DATABASE_URL=');
        putenv('SQLITE_PATH=' . $path);
        $this->temporarySqlitePath = $path;
    }

    private function cleanupIsolatedStore(): void
    {
        if ($this->temporarySqlitePath !== null && is_file($this->temporarySqlitePath)) {
            @unlink($this->temporarySqlitePath);
        }
    }

    private function characterWithBaseLoraAndOutfit(Store $store): array
    {
        foreach ($store->getCharacters() as $summary) {
            $character = $store->getCharacter((int) ($summary['id'] ?? 0));
            if (!is_array($character) || trim((string) ($character['base_lora_alias'] ?? '')) === '') {
                continue;
            }
            foreach (($character['outfits'] ?? []) as $outfit) {
                if (trim((string) ($outfit['prompt'] ?? '')) !== '') {
                    $character['_test_outfit'] = (string) ($outfit['name'] ?? '');
                    return $character;
                }
            }
        }

        return $this->createVerificationCharacter($store);
    }

    private function createVerificationCharacter(Store $store): array
    {
        $series = $store->saveSeries([
            'key' => 'verify_prompt_flow',
            'name' => 'Verify Prompt Flow',
            'source_type' => 'verification',
            'description' => 'Temporary verification fixture.',
            'base_lora_alias' => '',
            'base_lora_weight' => 1,
            'default_negative' => '',
            'nsfw_default' => true,
        ]);
        $character = $store->saveCharacter([
            'series_id' => (int) ($series['id'] ?? 0),
            'key' => 'verify_muse',
            'display_name' => 'Verify Muse',
            'full_name' => 'Verify Muse',
            'aliases' => ['verify muse'],
            'feature_tags' => 'verify muse, adult woman, confident expression',
            'adult_framing_tags' => 'adult woman, mature body, adult proportions',
            'base_lora_alias' => 'verify_character_lora',
            'base_lora_weight' => 0.8,
            'default_negative' => '',
            'source_type' => 'verification',
            'notes' => 'Generated by verify-prompt-flow.',
            'appearances' => [],
            'outfits' => [
                ['name' => 'Ninguno', 'prompt' => ''],
                ['name' => 'Default style', 'prompt' => 'verification outfit, fitted top'],
            ],
        ]);
        $character['_test_outfit'] = 'Default style';
        return $character;
    }

    private function baseInput(array $character): array
    {
        return [
            'uma' => (string) ($character['name'] ?? ''),
            'character_id' => (int) ($character['id'] ?? 0),
            'character_name' => (string) ($character['name'] ?? ''),
            'series_id' => (int) ($character['series_id'] ?? 0),
            'series_name' => (string) ($character['series_name'] ?? ''),
            'outfit' => '',
            'mode' => 'standard',
            'nsfw_enabled' => false,
            'nsfw_strict' => true,
            'loras' => [],
            'sd_payload' => ['seed' => -1],
        ];
    }

    private function verifyGlobalCensorshipGuard(PromptComposer $composer, array $character): void
    {
        $composed = $composer->compose($this->baseInput($character));
        $negative = mb_strtolower((string) ($composed['negative_prompt'] ?? ''));
        foreach (['censor bar', 'white censor bar', 'mosaic censoring', 'strategically covered'] as $term) {
            $this->assert(str_contains($negative, $term), "Standard mode negative prompt must include anti-censorship guard term {$term}.");
        }
        $this->assert(!str_contains(mb_strtolower((string) ($composed['prompt'] ?? '')), 'uncensored'), 'Standard mode must not add uncensored as a positive tag.');
        $this->assert(str_contains((string) ($composed['layers']['censorship_negative_guard'] ?? ''), 'censor bar'), 'Debug layers must expose censorship_negative_guard.');
    }

    private function verifyNsfwCensorshipGuard(PromptComposer $composer, array $character): void
    {
        foreach ([
            ['mode' => 'soft_nsfw', 'nsfw_intensity' => 'soft'],
            ['mode' => 'hard_nsfw', 'nsfw_intensity' => 'hard'],
        ] as $case) {
            $composed = $composer->compose(array_replace($this->baseInput($character), [
                'mode' => $case['mode'],
                'nsfw_enabled' => true,
                'nsfw_intensity' => $case['nsfw_intensity'],
                'nsfw_act' => '',
            ]));
            $negative = mb_strtolower((string) ($composed['negative_prompt'] ?? ''));
            foreach (['censor bar', 'privacy bar', 'censor blur'] as $term) {
                $this->assert(str_contains($negative, $term), "{$case['mode']} negative prompt must include anti-censorship guard term {$term}.");
            }
        }
    }

    private function verifyLlmPolishRemovesCensorshipTags(PromptComposer $composer): void
    {
        $method = new ReflectionMethod(PromptComposer::class, 'sanitizePolish');
        $method->setAccessible(true);
        $clean = (string) $method->invoke($composer, 'soft rim light, censor bar, mosaic censoring, strategically covered, white censor bar, cinematic lighting, uncensored', [
            'full_name' => '',
            'feature_tags' => '',
            'appearance_tags' => '',
            'outfit_tags' => '',
        ]);
        $lower = mb_strtolower($clean);
        foreach (['soft rim light', 'cinematic lighting', 'uncensored'] as $allowed) {
            $this->assert(str_contains($lower, $allowed), "LLM polish sanitizer must preserve non-censorship tag {$allowed}.");
        }
        foreach (['censor bar', 'mosaic censoring', 'strategically covered', 'white censor bar'] as $blocked) {
            $this->assert(!str_contains($lower, $blocked), "LLM polish sanitizer must remove censorship tag {$blocked}.");
        }
    }

    private function verifyHiresInheritsFinalNegativePrompt(): void
    {
        $index = (string) file_get_contents(dirname(__DIR__) . '/public/index.php');
        $this->assert(str_contains($index, '$payload[\'negative_prompt\'] ??'), 'Hires.fix must start hr_negative_prompt from the final negative prompt.');
    }

    private function verifyHardNsfwNoActIsNeutral(PromptComposer $composer, array $character): void
    {
        $composed = $composer->compose(array_replace($this->baseInput($character), [
            'mode' => 'hard_nsfw',
            'nsfw_enabled' => true,
            'nsfw_intensity' => 'hard',
            'nsfw_act' => '',
        ]));
        $directorText = mb_strtolower(implode(', ', [
            (string) ($composed['layers']['mode_tags'] ?? ''),
            (string) ($composed['layers']['nsfw_intensity'] ?? ''),
        ]));
        foreach (['blowjob', 'oral sex', 'dildo', 'vibrator', 'vaginal penetration', 'anal penetration', 'cum'] as $forbidden) {
            $this->assert(!str_contains($directorText, $forbidden), "hard_nsfw without act must not inject {$forbidden}");
        }
    }

    private function verifyStrictActBlocksIncompatibleLora(PromptAuditor $auditor, array $character): void
    {
        $audit = $auditor->audit(array_replace($this->baseInput($character), [
            'mode' => 'hard_nsfw',
            'nsfw_enabled' => true,
            'nsfw_strict' => true,
            'nsfw_act' => 'tit_fuck',
            'loras' => [[
                'alias' => 'verify_cowgirl_pose',
                'name' => 'verify_cowgirl_pose',
                'category' => 'pose',
                'trigger_words' => 'cowgirl position',
                'compatible_acts' => 'cowgirl_position',
                'incompatible_acts' => 'tit_fuck',
                'act_groups' => 'penetration',
                'enabled' => true,
            ]],
        ]));
        $this->assert($this->hasIssue($audit, 'lora_director.strict_act_incompatible', 'error'), 'Strict Act must block incompatible LoRA.');
    }

    private function verifyClothingLoraBlocksActiveOutfit(PromptAuditor $auditor, array $character): void
    {
        $audit = $auditor->audit(array_replace($this->baseInput($character), [
            'outfit' => (string) ($character['_test_outfit'] ?? ''),
            'loras' => [[
                'alias' => 'verify_clothing_lora',
                'name' => 'verify_clothing_lora',
                'category' => 'clothing',
                'trigger_words' => 'micro bikini',
                'conflict_groups' => 'clothing_primary',
                'requires_outfit_none' => true,
                'enabled' => true,
            ]],
        ]));
        $this->assert($this->hasIssue($audit, 'lora_director.outfit_conflict', 'error'), 'Clothing LoRA must block active outfit.');
    }

    private function verifyPoseBlockedByStrictAct(PromptAuditor $auditor, array $character): void
    {
        $audit = $auditor->audit(array_replace($this->baseInput($character), [
            'mode' => 'hard_nsfw',
            'nsfw_enabled' => true,
            'nsfw_strict' => true,
            'nsfw_act' => 'tit_fuck',
            'pose_enabled' => true,
            'pose_key' => 'arched_back',
        ]));
        $this->assert($this->hasIssue($audit, 'pose.blocked_by_strict_act', 'warning'), 'Pose incompatible with Strict Act must be reported.');
    }

    private function verifyCharacterLoraIdentityConflict(PromptAuditor $auditor, array $character): void
    {
        $audit = $auditor->audit(array_replace($this->baseInput($character), [
            'loras' => [[
                'alias' => 'verify_other_character_lora',
                'name' => 'verify_other_character_lora',
                'category' => 'character',
                'trigger_words' => 'other character',
                'conflict_groups' => 'character_identity',
                'enabled' => true,
            ]],
        ]));
        $this->assert($this->hasIssue($audit, 'lora_director.character_identity_conflict', 'error'), 'Character LoRA mismatch must be blocked.');
    }

    private function verifyCompatibleSeriesMismatch(PromptAuditor $auditor, array $character): void
    {
        $audit = $auditor->audit(array_replace($this->baseInput($character), [
            'loras' => [[
                'alias' => (string) ($character['base_lora_alias'] ?? 'verify_series_lora'),
                'name' => 'verify_series_lora',
                'category' => 'style',
                'trigger_words' => 'series locked style',
                'compatible_series' => 'definitely_not_the_selected_series',
                'enabled' => true,
            ]],
        ]));
        $this->assert($this->hasIssue($audit, 'lora_director.compatible_series_mismatch', 'error'), 'Compatible series mismatch must be blocked by backend.');
    }

    private function verifyFrontendAutoLlmFlow(): void
    {
        $root = dirname(__DIR__);
        $js = (string) file_get_contents($root . '/public/assets/app.js');
        $view = (string) file_get_contents($root . '/public/views/app.php');
        $this->assert(str_contains($view, 'id="autoLlmToggle"'), 'Auto LLM toggle must exist in the planner UI.');
        $this->assert(str_contains($js, 'AUTO_LLM_STORAGE_KEY'), 'Auto LLM state must be persisted.');
        $this->assert(str_contains($js, 'seedLockedLlmPolish'), 'Seed-locked LLM polish cache must exist.');
        $this->assert(preg_match('/async function generate\\(\\).*prepareAutoLlmForGeneration\\(\\).*runPromptAudit\\(\\)/s', $js) === 1, 'Generate must prepare Auto LLM before final audit.');
        $this->assert(str_contains($js, '_auto_llm'), 'Generate payload must include Auto LLM debug metadata.');
    }

    private function hasIssue(array $audit, string $code, string $severity): bool
    {
        foreach (($audit['issues'] ?? []) as $issue) {
            if (($issue['code'] ?? '') === $code && ($issue['severity'] ?? '') === $severity) {
                return true;
            }
        }
        return false;
    }

    private function assert(bool $condition, string $message): void
    {
        $this->checks++;
        if (!$condition) {
            throw new RuntimeException($message);
        }
    }
}

(new PromptFlowVerifier())->run();
